# ---------- Etapa 1: construir (si en el futuro agregas npm/vite) ----------
    FROM node:18-alpine AS build
    WORKDIR /app
    COPY Frontend /app
    
    # ---------- Etapa 2: servir con Nginx ----------
    FROM nginx:1.25-alpine
    COPY --from=build /app /usr/share/nginx/html
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]
    